service: python-serverless-fib

provider:
  name: aws
  runtime: python3.7

functions:
  fibonacci:
    name: fibonacci
    handler: handler.fib
    description: Calculates the Fibonacci sequence
    environment:
      CALC_LIMIT: 10
    events:
      - http:
          path: fib
          method: get
