service: python-serverless-fib

provider:
  name: aws
  runtime: python3.7

functions:
  fibonacci:
    name: fibonacci
    handler: app/aws_lambda.fib_sequence
    description: Calculates the Fibonacci sequence
    environment:
      CALC_LIMIT: 12
    events:
      - http:
          path: fib
          method: get
